os: linux
dist: xenial
language: python

stages:
  - lint
  - test

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

test: &test
  stage: test
  install:
    - pip install --upgrade pip
    - pip install poetry
    - poetry --version
    - poetry config virtualenvs.create false
    - poetry install --no-root -v
  script:
    - sh ./scripts/test.sh

jobs:
  include:
    - stage: lint
      python: "3.8"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - <<: *test
      python: "3.7"
    - <<: *test
      python: "3.8"
    - <<: *test
      python: "3.9"


after_success:
  - bash <(curl -s https://codecov.io/bash)
