language: python

dist: xenial

stages:
  - lint
  - test

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

jobs:
  include:
    - stage: lint
      python: "3.8"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: test
      python:
        - "3.8"
        - "3.9"
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry --version
        - poetry config virtualenvs.create false
        - poetry install --no-root -v
      script:
        - sh ./scripts/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
